title: Hello :)
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Nataša Nikolić # add your name
author-img: natash.jpg # add your photo
about-author: I am a psychologist interested in UX/UI design.  # add description
social-twitter: cococonati
# social-facebook: # add your Facebook handle
social-github: coconati
social-linkedin: # add your Linkedin handle
social-email: natasanikolic91@yahoo.com

# Disqus

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
